### ISSUE TITLE
Test fails on Isaiah's referred data

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/mri2mrs#3]
Test fails on Isaiah's referred data:

# DTI data downloaded from https://github.com/openmrslab/suspect/tree/master/tests/test_data/siemens/mri
# RDA file downloaded from https://github.com/openmrslab/suspect/tree/master/tests/test_data/siemens/

Can you run the following on any data that can be uploaded publicly?
* Requires pnl-zorro bashrc
* Requires python3

```
./mri2mrs.py --input any/t1/data.nrrd or .nii \
--labelMap any/rda/file --caseID random --region pcg --output ~/mri2mrs.test --mask
```

I ran the test on your referred data, I believe it failed due to incompatible dwi format. Please see `/home/tb571/Documents/mri2mrs/test_data/README` about how I created the test data.

To be more specific, I tried bot the following:
```
# nifti image
./mri2mrs.py -i test_data/A_DTI_axial_20140429161340_4.nii.gz \
-l test_data/SVS_30.rda -c abc -r pcg -o ~/mri2mrs.test -m

#nrrd image
./mri2mrs.py -i test_data/A_DTI_axial_20140429161340_4.nrrd \
-l test_data/SVS_30.rda -c abc -r pcg -o ~/mri2mrs.test -m

```

Also, I am not sure if we really want to run a test.

**Comment by tashrifbillah** [comment]
Based on Isaiah's opinion about running test, we shall merge the `command-logging` branch with `master` branch.

**Comment by ihnorton** [comment]
> I ran the test on your referred data, I believe it failed due to incompatible dwi format.

Where is this "A_DTI_axial_2014..." data coming from? We are not looking at dwi data right now, the goal is to use the T1 + RDA data in that directory.

If I convert the data in `https://github.com/openmrslab/suspect/tree/master/tests/test_data/siemens/mri` using dcm2niix then everything works fine:

```
(base) [tb571@pnl-z840-2 mri2mrs]$ ./mri2mrs.py -i /tmp/test_data/___20160429115930_3.nii -l test_data/SVS_30.rda -c abc -r pcg -o /tmp/test_data/mri2mrs.test -m
Creating mask and multiplying the input image by mask ...
Cannot perform requested swap (NEUROLOGICAL/RADIOLOGICAL storage inverted)
Try the following command instead:
fslswapdim abc-t1w-bet.nii.gz RL PA IS abc-t1w-bet.nii.gz
Segmenting T1 image to white/gray/CSF ...

Creating white, gray, csf separate images ...
Defining MRS on T1 image using MATLAB ...
matlab.run(['-singleCompThread', '-nojvm', '-nosplash', '-r', "diary('log-abc.txt'); addpath /home/tb571/Documents/mri2mrs; MRStoAnatomy('tmp-sb.nhdr', 'abc-t1w.nhdr', '/home/tb571/Documents/mri2mrs/test_data/SVS_30.rda', 'pcg_mask'); exit"], retcode=None)

                            < M A T L A B (R) >
                  Copyright 1984-2015 The MathWorks, Inc.
                   R2015b (8.6.0.267246) 64-bit (glnxa64)
                              August 20, 2015


For online documentation, see http://www.mathworks.com/support
For product information, visit www.mathworks.com.

The delimiter should be a non-empty char string.
Warning: MATLAB did not appear to successfully set the search path. To recover
for this session of MATLAB, type "restoredefaultpath;matlabrc". To find out how
to avoid this warning the next time you start MATLAB, type "docsearch problem
path" after recovering for this session.
Warning: Duplicate directory name: /home/tb571/matlab
Warning: Duplicate directory name:
/rfanfs/pnl-zorro/software/MATLAB/R2015b/toolbox/local

	Academic License

Warning: File is not RAS, make sure subsequent matlab processing is consistent!
Warning: File is not RAS, make sure subsequent matlab processing is consistent!

Cannot perform requested swap (NEUROLOGICAL/RADIOLOGICAL storage inverted)
Try the following command instead:
fslswapdim pcg_mask.nii.gz RL PA IS pcg_mask.nii.gz
Creating MRS masks ...
ROI volume:15889.228516
CSF volume:250.67968799999835
WM volume:7349.211914
GM volume:8289.336914
Program finished, see log-abc.txt for details
```

**Comment by ihnorton** [comment]
> Also, I am not sure if we really want to run a test.

I guess you mean because FAST is ... 🐢 slow? That's true, but for testing we can just cache the FAST output, because the T1 is not changing. The thing we want to *test* is this script.

**Comment by tashrifbillah** [comment]
`I believe it failed due to incompatible dwi format.`

Sorry, I didn't mean to say `dwi`, I understand it's a `T1 + RDA`. It looks like I also mistakenly input a `dwi` instead of a `T1`.

However, the testing is now successful. Thanks!
