### ISSUE TITLE
git-lfs requires sudo access

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/mri2mrs#5]
We tried on Josh's computer and it was discovered that `git-lfs` needed to write in `/usr/local/`. I hope this sudo access doesn't create any trouble with remote user installation and testing.

**Comment by tashrifbillah** [comment]
Also a problem for SlicerDiffusionQC

**Comment by ihnorton** [comment]
For user-only install run:

`PREFIX=$HOME ./install.sh`

**Comment by tashrifbillah** [comment]
Sorry, it didn't work.

**Comment by ihnorton** [comment]
How so? I just tried it when I commented...

**Comment by tashrifbillah** [comment]
Can you check Josh's Centos7? I installed using your suggestion, a `git-lfs` executable is created on /home/jeg88/Downloads. But, there is no `git lfs` command. Even the `git-lfs` doesn't work.

**Comment by ihnorton** [comment]
git-lfs needs to be somewhere in PATH. the command above adds it to `~/bin`, but `~/bin` was not in his PATH.

**Comment by ihnorton** [comment]
I fixed and tried it on his computer/account.

**Comment by tashrifbillah** [comment]
I'll add this instruction on the README then.
