### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by oferpasternak** [pnlbwh/mri2mrs#7]
Documentation of the -c parameter is not correct. Should be the case name.
(in "Program description")

**Comment by oferpasternak** [comment]
"An rda file from the scanner defining label map of a region (acg, agm, ltemp, pcg, pwm etc.); required" --> 
"An .rda MRS file from the scanner defining the coordinates of the region of interest"

Consider changing the name of this parameter from labelmap to rda_file or something else more relevant.

**Comment by tashrifbillah** [comment]
Hi Ofer, sorry about not noticing this earlier. I have followed your suggestion [here](https://github.com/pnlbwh/mri2mrs/commit/1949c10fd7e4d24acfc46d2a8f8381f5c1f4b0ae). Also, now the [tutorial](https://github.com/pnlbwh/mri2mrs) should have a much better look.
